---
abstract: 'Perl extension to create simple calendars'
author:
  - 'Dave Cross <dave@mag-sol.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.422, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Calendar-Simple
provides:
  Calendar::Simple:
    file: lib/Calendar/Simple.pm
    version: '1.23'
recommends:
  DateTime: '0'
requires:
  Carp: '0'
  Config: '0'
  Time::Local: '0'
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/davorg/calendar-simple
version: '1.23'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
