---
abstract: 'Perl extension to create simple calendars'
author:
  - 'Dave Cross <dave@mag-sol.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Calendar-Simple
provides:
  Calendar::Simple:
    file: lib/Calendar/Simple.pm
    version: 1.21
recommends:
  DateTime: 0
requires:
  Carp: 0
  Config: 0
  Time::Local: 0
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.21
