---
name: Calendar-Simple
version: 1.20
author:
  - 'Dave Cross <dave@mag-sol.com>'
abstract: Perl extension to create simple calendars
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Config: 0
  Time::Local: 0
  perl: 5.6.0
build_requires:
  Test::More: 0
recommends:
  DateTime: 0
provides:
  Calendar::Simple:
    file: lib/Calendar/Simple.pm
    version: 44
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
