---
name: Calendar-Simple
version: 1.13
author:
  - Dave Cross <dave@dave.org.uk>
abstract: Perl extension to create simple calendars
license: perl
requires:
  Test::More: 0
provides:
  Calendar::Simple:
    file: lib/Calendar/Simple.pm
    version: 1.13
generated_by: Module::Build version 0.261
